FROM node:22-alpine

RUN apk update && apk add bash
RUN mkdir /.npm-global && chown -R node:node /.npm-global
RUN mkdir /app && chown -R node:node /app

ENV NPM_CONFIG_PREFIX=/.npm-global
ENV PATH=$PATH:/.npm-global/bin

WORKDIR  /app

USER node

COPY --chown=node:node front/ ./

RUN npm cache clean --force
RUN npm install -g @angular/cli@19

CMD npm i && ng serve --host 0.0.0.0 --port 4200 --configuration=development